// Generated by `pnpm --filter @whosfree/backend db:types` (supabase gen types typescript)
// from supabase/migrations. Do not edit by hand.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      availability_prefs: {
        Row: {
          count_all_day_events: boolean;
          created_at: string;
          id: string;
          min_gap_minutes: number;
          user_id: string;
          weekly: NonNullable<Json>;
        };
        Insert: {
          count_all_day_events?: boolean;
          created_at?: string;
          id?: string;
          min_gap_minutes?: number;
          user_id: string;
          weekly?: NonNullable<Json>;
        };
        Update: {
          count_all_day_events?: boolean;
          created_at?: string;
          id?: string;
          min_gap_minutes?: number;
          user_id?: string;
          weekly?: NonNullable<Json>;
        };
        Relationships: [
          {
            foreignKeyName: 'availability_prefs_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: true;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
        ];
      };
      blocks: {
        Row: {
          blocked_id: string;
          blocker_id: string;
          created_at: string;
          id: string;
        };
        Insert: {
          blocked_id: string;
          blocker_id: string;
          created_at?: string;
          id?: string;
        };
        Update: {
          blocked_id?: string;
          blocker_id?: string;
          created_at?: string;
          id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'blocks_blocked_id_fkey';
            columns: ['blocked_id'];
            isOneToOne: false;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'blocks_blocker_id_fkey';
            columns: ['blocker_id'];
            isOneToOne: false;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
        ];
      };
      events: {
        Row: {
          busy: boolean;
          category: string | null;
          created_at: string;
          ends_at: string;
          exdates: string[];
          external_id: string | null;
          id: string;
          is_private: boolean;
          rrule: string | null;
          source_id: string;
          starts_at: string;
          title: string | null;
          user_id: string;
        };
        Insert: {
          busy?: boolean;
          category?: string | null;
          created_at?: string;
          ends_at: string;
          exdates?: string[];
          external_id?: string | null;
          id?: string;
          is_private?: boolean;
          rrule?: string | null;
          source_id: string;
          starts_at: string;
          title?: string | null;
          user_id: string;
        };
        Update: {
          busy?: boolean;
          category?: string | null;
          created_at?: string;
          ends_at?: string;
          exdates?: string[];
          external_id?: string | null;
          id?: string;
          is_private?: boolean;
          rrule?: string | null;
          source_id?: string;
          starts_at?: string;
          title?: string | null;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'events_source_same_user';
            columns: ['source_id', 'user_id'];
            isOneToOne: false;
            referencedRelation: 'sources';
            referencedColumns: ['id', 'user_id'];
          },
          {
            foreignKeyName: 'events_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
        ];
      };
      friendships: {
        Row: {
          created_at: string;
          id: string;
          requested_by: string;
          status: string;
          user_a: string;
          user_b: string;
        };
        Insert: {
          created_at?: string;
          id?: string;
          requested_by: string;
          status?: string;
          user_a: string;
          user_b: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          requested_by?: string;
          status?: string;
          user_a?: string;
          user_b?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'friendships_user_a_fkey';
            columns: ['user_a'];
            isOneToOne: false;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'friendships_user_b_fkey';
            columns: ['user_b'];
            isOneToOne: false;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
        ];
      };
      group_members: {
        Row: {
          can_edit_group: boolean;
          can_group_ping: boolean;
          can_invite: boolean;
          can_manage_members: boolean;
          created_at: string;
          group_id: string;
          id: string;
          joined_at: string;
          role: string;
          user_id: string;
        };
        Insert: {
          can_edit_group?: boolean;
          can_group_ping?: boolean;
          can_invite?: boolean;
          can_manage_members?: boolean;
          created_at?: string;
          group_id: string;
          id?: string;
          joined_at?: string;
          role?: string;
          user_id: string;
        };
        Update: {
          can_edit_group?: boolean;
          can_group_ping?: boolean;
          can_invite?: boolean;
          can_manage_members?: boolean;
          created_at?: string;
          group_id?: string;
          id?: string;
          joined_at?: string;
          role?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'group_members_group_id_fkey';
            columns: ['group_id'];
            isOneToOne: false;
            referencedRelation: 'groups';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'group_members_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
        ];
      };
      groups: {
        Row: {
          admin_id: string;
          created_at: string;
          emoji: string | null;
          id: string;
          join_mode: string;
          max_members: number;
          name: string;
        };
        Insert: {
          admin_id: string;
          created_at?: string;
          emoji?: string | null;
          id?: string;
          join_mode?: string;
          max_members?: number;
          name: string;
        };
        Update: {
          admin_id?: string;
          created_at?: string;
          emoji?: string | null;
          id?: string;
          join_mode?: string;
          max_members?: number;
          name?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'groups_admin_id_fkey';
            columns: ['admin_id'];
            isOneToOne: false;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
        ];
      };
      sources: {
        Row: {
          created_at: string;
          id: string;
          last_synced_at: string | null;
          period_end: string | null;
          period_exceptions: NonNullable<Json>;
          period_start: string | null;
          status: string;
          type: string;
          user_id: string;
        };
        Insert: {
          created_at?: string;
          id?: string;
          last_synced_at?: string | null;
          period_end?: string | null;
          period_exceptions?: NonNullable<Json>;
          period_start?: string | null;
          status?: string;
          type: string;
          user_id: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          last_synced_at?: string | null;
          period_end?: string | null;
          period_exceptions?: NonNullable<Json>;
          period_start?: string | null;
          status?: string;
          type?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'sources_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
        ];
      };
      users: {
        Row: {
          age_confirmed_at: string | null;
          avatar_url: string | null;
          birth_year: number | null;
          clerk_id: string;
          consent_at: string | null;
          consent_version: string | null;
          created_at: string;
          handle: string | null;
          id: string;
          name: string;
          sharing_paused: boolean;
          timezone: string;
        };
        Insert: {
          age_confirmed_at?: string | null;
          avatar_url?: string | null;
          birth_year?: number | null;
          clerk_id: string;
          consent_at?: string | null;
          consent_version?: string | null;
          created_at?: string;
          handle?: string | null;
          id?: string;
          name: string;
          sharing_paused?: boolean;
          timezone?: string;
        };
        Update: {
          age_confirmed_at?: string | null;
          avatar_url?: string | null;
          birth_year?: number | null;
          clerk_id?: string;
          consent_at?: string | null;
          consent_version?: string | null;
          created_at?: string;
          handle?: string | null;
          id?: string;
          name?: string;
          sharing_paused?: boolean;
          timezone?: string;
        };
        Relationships: [];
      };
      visibility_rules: {
        Row: {
          created_at: string;
          id: string;
          owner_id: string;
          target_id: string;
          target_type: string;
          tier: number;
        };
        Insert: {
          created_at?: string;
          id?: string;
          owner_id: string;
          target_id: string;
          target_type: string;
          tier?: number;
        };
        Update: {
          created_at?: string;
          id?: string;
          owner_id?: string;
          target_id?: string;
          target_type?: string;
          tier?: number;
        };
        Relationships: [
          {
            foreignKeyName: 'visibility_rules_owner_id_fkey';
            columns: ['owner_id'];
            isOneToOne: false;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
        ];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      accept_consent: { Args: { version: string }; Returns: string };
      account_status: {
        Args: Record<PropertyKey, never>;
        Returns: {
          age_confirmed: boolean;
          consent_required: boolean;
          consent_version: string;
          current_consent_version: string;
          has_profile: boolean;
        }[];
      };
      confirm_age: { Args: { birth_year: number }; Returns: string };
      current_consent_version: { Args: Record<PropertyKey, never>; Returns: string };
      current_user_id: { Args: Record<PropertyKey, never>; Returns: string };
      ensure_current_user: {
        Args: { avatar_url?: string; name: string; timezone?: string };
        Returns: {
          age_confirmed_at: string | null;
          avatar_url: string | null;
          birth_year: number | null;
          clerk_id: string;
          consent_at: string | null;
          consent_version: string | null;
          created_at: string;
          handle: string | null;
          id: string;
          name: string;
          sharing_paused: boolean;
          timezone: string;
        };
        SetofOptions: {
          from: '*';
          to: 'users';
          isOneToOne: true;
          isSetofReturn: false;
        };
      };
      events_for_viewer: {
        Args: { owner_id: string; range_end: string; range_start: string };
        Returns: {
          category: string;
          ends_at: string;
          exdates: string[];
          id: string;
          rrule: string;
          starts_at: string;
          title: string;
        }[];
      };
      set_day_hours: {
        Args: { day: string; end_time?: string; start_time?: string };
        Returns: Json;
      };
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

type DatabaseWithoutInternals = Omit<Database, '__InternalSupabase'>;

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, 'public'>];

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema['Tables'] & DefaultSchema['Views'])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])[TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema['Tables'] & DefaultSchema['Views'])
    ? (DefaultSchema['Tables'] & DefaultSchema['Views'])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R;
      }
      ? R
      : never
    : never;

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    keyof DefaultSchema['Tables'] | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Insert: infer I;
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I;
      }
      ? I
      : never
    : never;

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    keyof DefaultSchema['Tables'] | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Update: infer U;
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U;
      }
      ? U
      : never
    : never;

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    keyof DefaultSchema['Enums'] | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums']
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums'][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema['Enums']
    ? DefaultSchema['Enums'][DefaultSchemaEnumNameOrOptions]
    : never;

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    keyof DefaultSchema['CompositeTypes'] | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes']
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes'][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema['CompositeTypes']
    ? DefaultSchema['CompositeTypes'][PublicCompositeTypeNameOrOptions]
    : never;

export const Constants = {
  public: {
    Enums: {},
  },
} as const;
