// Generated by `pnpm --filter @whosfree/backend db:types` (supabase gen types typescript)
// from supabase/migrations. Do not edit by hand.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      availability_prefs: {
        Row: {
          count_all_day_events: boolean;
          created_at: string;
          id: string;
          min_gap_minutes: number;
          user_id: string;
          weekly: NonNullable<Json>;
        };
        Insert: {
          count_all_day_events?: boolean;
          created_at?: string;
          id?: string;
          min_gap_minutes?: number;
          user_id: string;
          weekly?: NonNullable<Json>;
        };
        Update: {
          count_all_day_events?: boolean;
          created_at?: string;
          id?: string;
          min_gap_minutes?: number;
          user_id?: string;
          weekly?: NonNullable<Json>;
        };
        Relationships: [
          {
            foreignKeyName: 'availability_prefs_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: true;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
        ];
      };
      blocks: {
        Row: {
          blocked_id: string;
          blocker_id: string;
          created_at: string;
          id: string;
        };
        Insert: {
          blocked_id: string;
          blocker_id: string;
          created_at?: string;
          id?: string;
        };
        Update: {
          blocked_id?: string;
          blocker_id?: string;
          created_at?: string;
          id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'blocks_blocked_id_fkey';
            columns: ['blocked_id'];
            isOneToOne: false;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'blocks_blocker_id_fkey';
            columns: ['blocker_id'];
            isOneToOne: false;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
        ];
      };
      events: {
        Row: {
          busy: boolean;
          category: string | null;
          created_at: string;
          ends_at: string;
          exdates: string[];
          external_id: string | null;
          id: string;
          is_private: boolean;
          offline_friend_id: string | null;
          rrule: string | null;
          source_id: string;
          starts_at: string;
          title: string | null;
          user_id: string;
        };
        Insert: {
          busy?: boolean;
          category?: string | null;
          created_at?: string;
          ends_at: string;
          exdates?: string[];
          external_id?: string | null;
          id?: string;
          is_private?: boolean;
          offline_friend_id?: string | null;
          rrule?: string | null;
          source_id: string;
          starts_at: string;
          title?: string | null;
          user_id: string;
        };
        Update: {
          busy?: boolean;
          category?: string | null;
          created_at?: string;
          ends_at?: string;
          exdates?: string[];
          external_id?: string | null;
          id?: string;
          is_private?: boolean;
          offline_friend_id?: string | null;
          rrule?: string | null;
          source_id?: string;
          starts_at?: string;
          title?: string | null;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'events_offline_friend_same_user';
            columns: ['offline_friend_id', 'user_id'];
            isOneToOne: false;
            referencedRelation: 'offline_friends';
            referencedColumns: ['id', 'user_id'];
          },
          {
            foreignKeyName: 'events_source_same_user';
            columns: ['source_id', 'user_id'];
            isOneToOne: false;
            referencedRelation: 'sources';
            referencedColumns: ['id', 'user_id'];
          },
          {
            foreignKeyName: 'events_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
        ];
      };
      friendships: {
        Row: {
          created_at: string;
          id: string;
          requested_by: string;
          status: string;
          user_a: string;
          user_b: string;
        };
        Insert: {
          created_at?: string;
          id?: string;
          requested_by: string;
          status?: string;
          user_a: string;
          user_b: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          requested_by?: string;
          status?: string;
          user_a?: string;
          user_b?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'friendships_user_a_fkey';
            columns: ['user_a'];
            isOneToOne: false;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'friendships_user_b_fkey';
            columns: ['user_b'];
            isOneToOne: false;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
        ];
      };
      group_members: {
        Row: {
          can_edit_group: boolean;
          can_group_ping: boolean;
          can_invite: boolean;
          can_manage_members: boolean;
          created_at: string;
          group_id: string;
          id: string;
          joined_at: string;
          role: string;
          user_id: string;
        };
        Insert: {
          can_edit_group?: boolean;
          can_group_ping?: boolean;
          can_invite?: boolean;
          can_manage_members?: boolean;
          created_at?: string;
          group_id: string;
          id?: string;
          joined_at?: string;
          role?: string;
          user_id: string;
        };
        Update: {
          can_edit_group?: boolean;
          can_group_ping?: boolean;
          can_invite?: boolean;
          can_manage_members?: boolean;
          created_at?: string;
          group_id?: string;
          id?: string;
          joined_at?: string;
          role?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'group_members_group_id_fkey';
            columns: ['group_id'];
            isOneToOne: false;
            referencedRelation: 'groups';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'group_members_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
        ];
      };
      groups: {
        Row: {
          admin_id: string;
          created_at: string;
          emoji: string | null;
          id: string;
          join_mode: string;
          max_members: number;
          name: string;
        };
        Insert: {
          admin_id: string;
          created_at?: string;
          emoji?: string | null;
          id?: string;
          join_mode?: string;
          max_members?: number;
          name: string;
        };
        Update: {
          admin_id?: string;
          created_at?: string;
          emoji?: string | null;
          id?: string;
          join_mode?: string;
          max_members?: number;
          name?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'groups_admin_id_fkey';
            columns: ['admin_id'];
            isOneToOne: false;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
        ];
      };
      invites: {
        Row: {
          code: string;
          created_at: string;
          expires_at: string | null;
          group_id: string | null;
          id: string;
          inviter_id: string;
          max_uses: number | null;
          revoked: boolean;
          uses: number;
        };
        Insert: {
          code: string;
          created_at?: string;
          expires_at?: string | null;
          group_id?: string | null;
          id?: string;
          inviter_id: string;
          max_uses?: number | null;
          revoked?: boolean;
          uses?: number;
        };
        Update: {
          code?: string;
          created_at?: string;
          expires_at?: string | null;
          group_id?: string | null;
          id?: string;
          inviter_id?: string;
          max_uses?: number | null;
          revoked?: boolean;
          uses?: number;
        };
        Relationships: [
          {
            foreignKeyName: 'invites_group_id_fkey';
            columns: ['group_id'];
            isOneToOne: false;
            referencedRelation: 'groups';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'invites_inviter_id_fkey';
            columns: ['inviter_id'];
            isOneToOne: false;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
        ];
      };
      offline_friends: {
        Row: {
          created_at: string;
          emoji: string | null;
          id: string;
          nickname: string;
          permission_confirmed_at: string;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          created_at?: string;
          emoji?: string | null;
          id?: string;
          nickname: string;
          permission_confirmed_at: string;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          created_at?: string;
          emoji?: string | null;
          id?: string;
          nickname?: string;
          permission_confirmed_at?: string;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'offline_friends_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
        ];
      };
      pings: {
        Row: {
          created_at: string;
          expires_at: string;
          group_id: string | null;
          id: string;
          read_at: string | null;
          recipient_id: string;
          replied_at: string | null;
          reply: string | null;
          reply_read_at: string | null;
          reply_text: string | null;
          sender_id: string;
          template: string | null;
          text: string | null;
        };
        Insert: {
          created_at?: string;
          expires_at: string;
          group_id?: string | null;
          id?: string;
          read_at?: string | null;
          recipient_id: string;
          replied_at?: string | null;
          reply?: string | null;
          reply_read_at?: string | null;
          reply_text?: string | null;
          sender_id: string;
          template?: string | null;
          text?: string | null;
        };
        Update: {
          created_at?: string;
          expires_at?: string;
          group_id?: string | null;
          id?: string;
          read_at?: string | null;
          recipient_id?: string;
          replied_at?: string | null;
          reply?: string | null;
          reply_read_at?: string | null;
          reply_text?: string | null;
          sender_id?: string;
          template?: string | null;
          text?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'pings_group_id_fkey';
            columns: ['group_id'];
            isOneToOne: false;
            referencedRelation: 'groups';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'pings_recipient_id_fkey';
            columns: ['recipient_id'];
            isOneToOne: false;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'pings_sender_id_fkey';
            columns: ['sender_id'];
            isOneToOne: false;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
        ];
      };
      push_subscriptions: {
        Row: {
          auth: string;
          created_at: string;
          device_label: string | null;
          endpoint: string;
          id: string;
          last_used_at: string | null;
          p256dh: string;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          auth: string;
          created_at?: string;
          device_label?: string | null;
          endpoint: string;
          id?: string;
          last_used_at?: string | null;
          p256dh: string;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          auth?: string;
          created_at?: string;
          device_label?: string | null;
          endpoint?: string;
          id?: string;
          last_used_at?: string | null;
          p256dh?: string;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'push_subscriptions_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
        ];
      };
      rate_limits: {
        Row: {
          action: string;
          count: number;
          created_at: string;
          user_id: string;
          window_end: string;
          window_start: string;
        };
        Insert: {
          action: string;
          count?: number;
          created_at?: string;
          user_id: string;
          window_end: string;
          window_start: string;
        };
        Update: {
          action?: string;
          count?: number;
          created_at?: string;
          user_id?: string;
          window_end?: string;
          window_start?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'rate_limits_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
        ];
      };
      sources: {
        Row: {
          created_at: string;
          id: string;
          last_synced_at: string | null;
          offline_friend_id: string | null;
          period_end: string | null;
          period_exceptions: NonNullable<Json>;
          period_start: string | null;
          status: string;
          type: string;
          user_id: string;
        };
        Insert: {
          created_at?: string;
          id?: string;
          last_synced_at?: string | null;
          offline_friend_id?: string | null;
          period_end?: string | null;
          period_exceptions?: NonNullable<Json>;
          period_start?: string | null;
          status?: string;
          type: string;
          user_id: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          last_synced_at?: string | null;
          offline_friend_id?: string | null;
          period_end?: string | null;
          period_exceptions?: NonNullable<Json>;
          period_start?: string | null;
          status?: string;
          type?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'sources_offline_friend_same_user';
            columns: ['offline_friend_id', 'user_id'];
            isOneToOne: false;
            referencedRelation: 'offline_friends';
            referencedColumns: ['id', 'user_id'];
          },
          {
            foreignKeyName: 'sources_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
        ];
      };
      status_overrides: {
        Row: {
          created_at: string;
          ends_at: string | null;
          id: string;
          label: string | null;
          starts_at: string;
          status: string;
          user_id: string;
        };
        Insert: {
          created_at?: string;
          ends_at?: string | null;
          id?: string;
          label?: string | null;
          starts_at?: string;
          status: string;
          user_id: string;
        };
        Update: {
          created_at?: string;
          ends_at?: string | null;
          id?: string;
          label?: string | null;
          starts_at?: string;
          status?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'status_overrides_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
        ];
      };
      users: {
        Row: {
          age_confirmed_at: string | null;
          avatar_url: string | null;
          birth_year: number | null;
          clerk_id: string;
          consent_at: string | null;
          consent_version: string | null;
          created_at: string;
          handle: string | null;
          id: string;
          name: string;
          sharing_paused: boolean;
          timezone: string;
        };
        Insert: {
          age_confirmed_at?: string | null;
          avatar_url?: string | null;
          birth_year?: number | null;
          clerk_id: string;
          consent_at?: string | null;
          consent_version?: string | null;
          created_at?: string;
          handle?: string | null;
          id?: string;
          name: string;
          sharing_paused?: boolean;
          timezone?: string;
        };
        Update: {
          age_confirmed_at?: string | null;
          avatar_url?: string | null;
          birth_year?: number | null;
          clerk_id?: string;
          consent_at?: string | null;
          consent_version?: string | null;
          created_at?: string;
          handle?: string | null;
          id?: string;
          name?: string;
          sharing_paused?: boolean;
          timezone?: string;
        };
        Relationships: [];
      };
      visibility_rules: {
        Row: {
          created_at: string;
          id: string;
          owner_id: string;
          target_id: string;
          target_type: string;
          tier: number;
        };
        Insert: {
          created_at?: string;
          id?: string;
          owner_id: string;
          target_id: string;
          target_type: string;
          tier?: number;
        };
        Update: {
          created_at?: string;
          id?: string;
          owner_id?: string;
          target_id?: string;
          target_type?: string;
          tier?: number;
        };
        Relationships: [
          {
            foreignKeyName: 'visibility_rules_owner_id_fkey';
            columns: ['owner_id'];
            isOneToOne: false;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
        ];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      accept_consent: { Args: { version: string }; Returns: string };
      accept_friend_request: { Args: { tier?: number; user_id: string }; Returns: undefined };
      account_status: {
        Args: Record<PropertyKey, never>;
        Returns: {
          age_confirmed: boolean;
          consent_required: boolean;
          consent_version: string;
          current_consent_version: string;
          has_profile: boolean;
        }[];
      };
      block_user: { Args: { user_id: string }; Returns: undefined };
      cancel_friend_request: { Args: { user_id: string }; Returns: undefined };
      clear_status: { Args: Record<PropertyKey, never>; Returns: undefined };
      commit_schedule: {
        Args: { draft: Json; offline_friend_id?: string; source_type?: string };
        Returns: string;
      };
      confirm_age: { Args: { birth_year: number }; Returns: string };
      create_group: { Args: { emoji?: string; name: string; tier?: number }; Returns: string };
      create_group_invite: {
        Args: { expires_at?: string; group_id: string; max_uses?: number };
        Returns: Database['public']['CompositeTypes']['group_invite'];
        SetofOptions: {
          from: '*';
          to: 'group_invite';
          isOneToOne: true;
          isSetofReturn: false;
        };
      };
      create_offline_friend: {
        Args: { emoji?: string; nickname: string; permission_confirmed?: boolean };
        Returns: string;
      };
      current_consent_version: { Args: Record<PropertyKey, never>; Returns: string };
      current_user_id: { Args: Record<PropertyKey, never>; Returns: string };
      decline_friend_request: { Args: { user_id: string }; Returns: undefined };
      delete_group: { Args: { group_id: string }; Returns: undefined };
      delete_offline_friend: { Args: { offline_friend_id: string }; Returns: undefined };
      delete_push_subscription: { Args: { endpoint: string }; Returns: boolean };
      ensure_current_user: {
        Args: { avatar_url?: string; name: string; timezone?: string };
        Returns: {
          age_confirmed_at: string | null;
          avatar_url: string | null;
          birth_year: number | null;
          clerk_id: string;
          consent_at: string | null;
          consent_version: string | null;
          created_at: string;
          handle: string | null;
          id: string;
          name: string;
          sharing_paused: boolean;
          timezone: string;
        };
        SetofOptions: {
          from: '*';
          to: 'users';
          isOneToOne: true;
          isSetofReturn: false;
        };
      };
      events_for_viewer: {
        Args: { owner_id: string; range_end: string; range_start: string };
        Returns: {
          category: string;
          ends_at: string;
          exdates: string[];
          id: string;
          rrule: string;
          starts_at: string;
          title: string;
        }[];
      };
      find_user_by_handle: {
        Args: { lookup: string };
        Returns: {
          avatar_url: string;
          handle: string;
          id: string;
          name: string;
          relationship: string;
        }[];
      };
      get_group_members: {
        Args: { group_id: string };
        Returns: {
          avatar_url: string;
          can_edit_group: boolean;
          can_group_ping: boolean;
          can_invite: boolean;
          can_manage_members: boolean;
          handle: string;
          is_me: boolean;
          joined_at: string;
          name: string;
          role: string;
          user_id: string;
        }[];
      };
      get_invite_summary: {
        Args: { code: string };
        Returns: {
          group_emoji: string;
          group_name: string;
          inviter_name: string;
          member_count: number;
          status: string;
        }[];
      };
      get_profile: {
        Args: { user_id: string };
        Returns: {
          avatar_url: string;
          handle: string;
          id: string;
          name: string;
          relationship: string;
        }[];
      };
      join_group: { Args: { code: string; tier?: number }; Returns: string };
      leave_group: { Args: { group_id: string }; Returns: undefined };
      list_blocked_users: {
        Args: Record<PropertyKey, never>;
        Returns: {
          avatar_url: string;
          blocked_at: string;
          handle: string;
          name: string;
          user_id: string;
        }[];
      };
      list_friend_requests: {
        Args: Record<PropertyKey, never>;
        Returns: {
          avatar_url: string;
          direction: string;
          handle: string;
          name: string;
          requested_at: string;
          tier: number;
          user_id: string;
        }[];
      };
      list_friends: {
        Args: Record<PropertyKey, never>;
        Returns: {
          avatar_url: string;
          handle: string;
          name: string;
          tier: number;
          user_id: string;
        }[];
      };
      list_group_invites: {
        Args: { group_id: string };
        Returns: Database['public']['CompositeTypes']['group_invite'][];
        SetofOptions: {
          from: '*';
          to: 'group_invite';
          isOneToOne: false;
          isSetofReturn: true;
        };
      };
      list_inbox: {
        Args: Record<PropertyKey, never>;
        Returns: {
          created_at: string;
          direction: string;
          expires_at: string;
          id: string;
          other_avatar_url: string;
          other_handle: string;
          other_id: string;
          other_name: string;
          replied_at: string;
          reply: string;
          reply_text: string;
          template: string;
          text: string;
          unread: boolean;
        }[];
      };
      list_my_groups: {
        Args: Record<PropertyKey, never>;
        Returns: {
          can_edit_group: boolean;
          can_group_ping: boolean;
          can_invite: boolean;
          can_manage_members: boolean;
          emoji: string;
          id: string;
          joined_at: string;
          max_members: number;
          member_count: number;
          my_tier: number;
          name: string;
          role: string;
        }[];
      };
      list_offline_friends: {
        Args: Record<PropertyKey, never>;
        Returns: {
          created_at: string;
          emoji: string;
          has_schedule: boolean;
          id: string;
          nickname: string;
          permission_confirmed_at: string;
          updated_at: string;
        }[];
      };
      mark_pings_read: { Args: { ping_ids?: string[] }; Returns: number };
      now_for_viewer: {
        Args: { range_end?: string; range_start?: string };
        Returns: {
          available_hours: Json;
          avatar_url: string;
          group_ids: string[];
          handle: string;
          has_schedule: boolean;
          name: string;
          overrides: Json;
          paused: boolean;
          relationship: string;
          sources: Json;
          tier: number;
          timezone: string;
          user_id: string;
        }[];
      };
      regenerate_group_invite: {
        Args: { invite_id: string };
        Returns: Database['public']['CompositeTypes']['group_invite'];
        SetofOptions: {
          from: '*';
          to: 'group_invite';
          isOneToOne: true;
          isSetofReturn: false;
        };
      };
      remove_group_member: { Args: { group_id: string; user_id: string }; Returns: undefined };
      reply_to_ping: {
        Args: { message?: string; ping_id: string; reply?: string };
        Returns: {
          notify: boolean;
          replier_name: string;
          sender_id: string;
        }[];
      };
      request_test_push: { Args: Record<PropertyKey, never>; Returns: string };
      revoke_group_invite: { Args: { invite_id: string }; Returns: undefined };
      save_push_subscription: {
        Args: { auth: string; device_label?: string; endpoint: string; p256dh: string };
        Returns: string;
      };
      send_friend_request: { Args: { tier?: number; user_id: string }; Returns: string };
      send_friend_request_by_handle: { Args: { handle: string; tier?: number }; Returns: string };
      send_ping: {
        Args: { confirmed?: boolean; message?: string; recipient: string; template?: string };
        Returns: {
          notify: boolean;
          ping_id: string;
          recipient_id: string;
          sender_name: string;
        }[];
      };
      set_day_hours: {
        Args: { day: string; end_time?: string; start_time?: string };
        Returns: Json;
      };
      set_group_member_permissions: {
        Args: {
          can_edit_group?: boolean;
          can_group_ping?: boolean;
          can_invite?: boolean;
          can_manage_members?: boolean;
          group_id: string;
          user_id: string;
        };
        Returns: undefined;
      };
      set_handle: { Args: { handle: string }; Returns: string };
      set_status: {
        Args: { ends_at?: string; label?: string; status: string };
        Returns: {
          created_at: string;
          ends_at: string | null;
          id: string;
          label: string | null;
          starts_at: string;
          status: string;
          user_id: string;
        };
        SetofOptions: {
          from: '*';
          to: 'status_overrides';
          isOneToOne: true;
          isSetofReturn: false;
        };
      };
      transfer_group_admin: {
        Args: { group_id: string; new_admin_id: string };
        Returns: undefined;
      };
      unblock_user: { Args: { user_id: string }; Returns: undefined };
      unfriend: { Args: { user_id: string }; Returns: undefined };
      unread_ping_count: { Args: Record<PropertyKey, never>; Returns: number };
      update_group: { Args: { emoji: string; group_id: string; name: string }; Returns: undefined };
      update_offline_friend: {
        Args: { emoji: string; nickname: string; offline_friend_id: string };
        Returns: undefined;
      };
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      group_invite: {
        id: string | null;
        code: string | null;
        expires_at: string | null;
        max_uses: number | null;
        uses: number | null;
        created_at: string | null;
        created_by_me: boolean | null;
      };
    };
  };
};

type DatabaseWithoutInternals = Omit<Database, '__InternalSupabase'>;

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, 'public'>];

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema['Tables'] & DefaultSchema['Views'])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])[TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema['Tables'] & DefaultSchema['Views'])
    ? (DefaultSchema['Tables'] & DefaultSchema['Views'])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R;
      }
      ? R
      : never
    : never;

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    keyof DefaultSchema['Tables'] | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Insert: infer I;
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I;
      }
      ? I
      : never
    : never;

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    keyof DefaultSchema['Tables'] | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Update: infer U;
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U;
      }
      ? U
      : never
    : never;

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    keyof DefaultSchema['Enums'] | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums']
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums'][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema['Enums']
    ? DefaultSchema['Enums'][DefaultSchemaEnumNameOrOptions]
    : never;

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    keyof DefaultSchema['CompositeTypes'] | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes']
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes'][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema['CompositeTypes']
    ? DefaultSchema['CompositeTypes'][PublicCompositeTypeNameOrOptions]
    : never;

export const Constants = {
  public: {
    Enums: {},
  },
} as const;
