// Runs the real Supabase CLI against the schema without Docker: the schema is
// built in PGlite (Supabase shim + every migration) and served over the
// Postgres wire protocol with @electric-sql/pglite-socket, and the CLI
// connects to it with --db-url. Used by scripts/gen-types.ts (db:types) and
// test/cli.test.ts.

import { execFile } from 'node:child_process';
import { join } from 'node:path';
import { promisify } from 'node:util';
import { PGlite } from '@electric-sql/pglite';
import { PGLiteSocketServer } from '@electric-sql/pglite-socket';
import { format, resolveConfig } from 'prettier';
import { applySchema } from '../test/harness/db';

const PACKAGE_ROOT = join(import.meta.dirname, '..');
export const TYPES_PATH = join(PACKAGE_ROOT, 'src', 'database.types.ts');
const SUPABASE_BIN = join(PACKAGE_ROOT, 'node_modules', '.bin', 'supabase');

const HEADER = `// Generated by \`pnpm --filter @synkd/backend db:types\` (supabase gen types typescript)
// from supabase/migrations. Do not edit by hand.

`;

/** Runs the Supabase CLI from the package directory; returns stdout. */
export async function supabaseCli(args: string[]): Promise<string> {
  const { stdout } = await promisify(execFile)(SUPABASE_BIN, args, {
    cwd: PACKAGE_ROOT,
    maxBuffer: 16 * 1024 * 1024,
  });
  return stdout;
}

/** Serves `pg` on a local TCP port for the duration of `fn`, passing it a connection URL. */
export async function servePglite<T>(pg: PGlite, fn: (dbUrl: string) => Promise<T>): Promise<T> {
  const port = 20_000 + Math.floor(Math.random() * 20_000);
  const server = new PGLiteSocketServer({ db: pg, host: '127.0.0.1', port });
  await server.start();
  try {
    return await fn(`postgresql://postgres:postgres@127.0.0.1:${port}/postgres?sslmode=disable`);
  } finally {
    await server.stop();
  }
}

/** Returns the contents of src/database.types.ts, generated from the migrations (or from `dbUrl`). */
export async function generateTypes(dbUrl?: string): Promise<string> {
  const gen = (url: string) =>
    supabaseCli(['gen', 'types', 'typescript', '--db-url', url, '--schema', 'public']);
  let raw: string;
  if (dbUrl) {
    raw = await gen(dbUrl);
  } else {
    const pg = await PGlite.create();
    try {
      await applySchema(pg);
      raw = await servePglite(pg, gen);
    } finally {
      await pg.close();
    }
  }
  if (!raw.includes('export type Database')) {
    throw new Error('supabase gen types produced no Database type');
  }
  const config = await resolveConfig(TYPES_PATH);
  return format(HEADER + raw, { ...config, filepath: TYPES_PATH });
}
